config:
  selfUrl: https://eshop-st-gateway-public-web
  globalConfigurationBaseUrl: http://eshop-st-gateway-public-web
  authServer:
    authority: http://eshop-st-authserver
    requireHttpsMetadata: "false"
    swaggerClientId: WebGateway_Swagger
    swaggerClientSecret: "1q2w3e*"
  dotnetEnv: Staging 
  redisHost: es-st-redis
  rabbitmqHost: es-st-rabbitmq
  elasticsearchHost: #
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8

reRoutes:
  accountService:
    url: http://eshop-st-authserver
  identityService:
    url: http://eshop-st-identity
  administrationService:
    url: http://eshop-st-administration
  catalogService:
    url: http://eshop-st-catalog
  basketService:
    url: http://eshop-st-basket
  orderingService:
    url: http://eshop-st-ordering
  paymentService:
    url: http://eshop-st-payment  

ingress:
  host: eshop-st-gateway-web-public
  tlsSecret: eshop-demo-tls

image:
  repository: eshoponabp/gateway-web-public
  tag: latest
  pullPolicy: IfNotPresent

env: {}
    