apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}-configmap
data:
  yarp.json: |-
    {
    "ReverseProxy": {
      "Routes": {
        "AbpApi": {
          "ClusterId": "administrationCluster",
          "Match": {
            "Path": "/api/abp/{**catch-all}"
          }
        },
        "IdentityService": {
          "ClusterId": "identityCluster",
          "Match": {
            "Path": "/api/identity/{**everything}"
          }
        },
        "IdentityServiceSwagger": {
          "ClusterId": "identityCluster",
          "Match": {
            "Path": "/swagger-json/Identity/swagger/v1/swagger.json"
          },
          "Transforms": [
            { "PathRemovePrefix": "/swagger-json/Identity" }
          ]
        },
        "FeatureManagement": {
          "ClusterId": "administrationCluster",
          "Match": {
            "Path": "/api/feature-management/{**everything}"
          }
        },
        "PermissionManagement": {
          "ClusterId": "administrationCluster",
          "Match": {
            "Path": "/api/permission-management/{**everything}"
          }
        },
        "SettingManagement": {
          "ClusterId": "administrationCluster",
          "Match": {
            "Path": "/api/setting-management/{**everything}"
          }
        },
        "AdministrationServiceSwagger": {
          "ClusterId": "administrationCluster",
          "Match": {
            "Path": "/swagger-json/Administration/swagger/v1/swagger.json"
          },
          "Transforms": [
            { "PathRemovePrefix": "/swagger-json/Administration" }
          ]
        },
        "CatalogService": {
          "ClusterId": "catalogCluster",
          "Match": {
            "Path": "/api/catalog/{**everything}"
          }
        },
        "CatalogServiceSwagger": {
          "ClusterId": "catalogCluster",
          "Match": {
            "Path": "/swagger-json/Catalog/swagger/v1/swagger.json"
          },
          "Transforms": [
            { "PathRemovePrefix": "/swagger-json/Catalog" }
          ]
        },
        "product-picture-route": {
          "ClusterId": "catalogCluster",
          "Match": {
            "Path": "/product-images/{**everything}",
            "Methods": [ "GET" ]
          }
        },
        "BasketService": {
          "ClusterId": "basketCluster",
          "Match": {
            "Path": "/api/basket/{**everything}"
          }
        },
        "OrderingService": {
          "ClusterId": "orderingCluster",
          "Match": {
            "Path": "/api/ordering/{**everything}"
          }
        },
        "OrderingServiceSwagger": {
          "ClusterId": "orderingCluster",
          "Match": {
            "Path": "/swagger-json/Ordering/swagger/v1/swagger.json"
          },
          "Transforms": [
            { "PathRemovePrefix": "/swagger-json/Ordering" }
          ]
        },
        "CmskitService": {
          "ClusterId": "cmskitCluster",
          "Match": {
            "Path": "/api/cmskit/{**everything}"
          }
        },
        "CmskitServiceSwagger": {
          "ClusterId": "cmskitCluster",
          "Match": {
            "Path": "/swagger-json/Cmskit/swagger/v1/swagger.json"
          },
          "Transforms": [
            { "PathRemovePrefix": "/swagger-json/Cmskit" }
          ]
        },
        "PaymentService": {
          "ClusterId": "paymentCluster",
          "Match": {
            "Path": "/api/payment/{**everything}"
          }
        },
        "PaymentServiceSwagger": {
          "ClusterId": "paymentCluster",
          "Match": {
            "Path": "/swagger-json/payment/swagger/v1/swagger.json"
          },
          "Transforms": [
            { "PathRemovePrefix": "/swagger-json/payment" }
          ]
        },
      },
      "Clusters": {
        "identityCluster": {
          "Destinations": {
            "destination1": {
              "Address": "{{ .Values.reRoutes.identityService.url }}"
            }
          }
        },
        "administrationCluster": {
          "Destinations": {
            "destination1": {
              "Address": "{{ .Values.reRoutes.administrationService.url }}"
            }
          }
        },
        "catalogCluster": {
          "Destinations": {
            "destination1": {
              "Address": "{{ .Values.reRoutes.catalogService.url }}"
            }
          }
        },
        "basketCluster": {
          "Destinations": {
            "destination1": {
              "Address": "{{ .Values.reRoutes.basketService.url }}"
            }
          }
        },
        "orderingCluster": {
          "Destinations": {
            "destination1": {
              "Address": "{{ .Values.reRoutes.orderingService.url }}"
            }
          }
        },
        "cmskitCluster": {
          "Destinations": {
            "destination1": {
              "Address": "{{ .Values.reRoutes.cmskitService.url }}"
            }
          }
        },
        "paymentCluster": {
          "Destinations": {
            "destination1": {
              "Address": "{{ .Values.reRoutes.paymentService.url }}"
            }
          }
        }
      }
    }
    }