config:
  selfUrl: https://eshop-st-saas
  corsOrigins: https://eshop-st-gateway-web,https://eshop-st-gateway-public-web,https://eshop-st-gateway-internal
  connectionStrings:
    administrationService: "Server=es-st-sqldb,1433;Database=EShopOnAbp_Administration;User Id=sa;password=myPassw@rd;MultipleActiveResultSets=true"
    saasService: "Server=es-st-sqldb,1433;Database=EShopOnAbp_Saas;User Id=sa;password=myPassw@rd;MultipleActiveResultSets=true"
  authServer:
    authority: http://eshop-st-authserver
    requireHttpsMetadata: "false"
  dotnetEnv: Staging
  redisHost: es-st-redis
  rabbitmqHost: es-st-rabbitmq
  elasticsearchHost: es-st-elasticsearch
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8

ingress:
  host: eshop-st-saas
  tlsSecret: eshop-demo-tls

image:
  repository: eshoponabp/service-saas
  tag: latest
  pullPolicy: IfNotPresent

env: {}      