config:
  selfUrl: https://www.admin.eshoponabp.com
  gatewayUrl: "https://www.gateway.eshoponabp.com/"
  authServer:
    authority: https://auth.eshoponabp.com
    requireHttpsMetadata: "false"

ingress:
  host: eshop-st-web
  tlsSecret: eshop-wildcard-tls

image:
  repository: eshoponabp/app-web
  tag: latest
  pullPolicy: IfNotPresent

# Extra environment variables or configurations
env: {}
