version: '3.7'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management-alpine
    networks: 
      - eshoponabp-network
      
  redis:
    container_name: redis
    image: redis:alpine
    networks: 
      - eshoponabp-network
    
  sql-server-db:
    container_name: sql-server-db
    image: mcr.microsoft.com/mssql/server
    volumes:
      - sqldata:/var/opt/mssql
    networks: 
      - eshoponabp-network
      
volumes:
  sqldata:

networks:
  eshoponabp-network:
    external: true