version: '3.7'

services:
  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    ports:
      - "6379:6379"
      
  postgres-db:
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "myPassw0rd"
