version: '3.7'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management-alpine
    networks: 
      - eshoponabp-network
      
  redis:
    container_name: redis
    image: redis:alpine
    networks: 
      - eshoponabp-network
    
  postgres-db:
    container_name: postgres-db
    image: postgres:14.1
    volumes:
      - sqldata:/var/opt/postgres
    networks: 
      - eshoponabp-network
      
volumes:
  sqldata:

networks:
  eshoponabp-network:
    external: true