config:
  selfUrl: https://auth.eshoponabp.com   
  corsOrigins: https://gateway.eshoponabp.com,https://gateway-public.eshoponabp.com,https://identity.eshoponabp.com,https://administration.eshoponabp.com,https://basket.eshoponabp.com,https://catalog.eshoponabp.com,https://order.eshoponabp.com,https://payment.eshoponabp.com,https://admin.eshoponabp.com,https://www.eshoponabp.com
  allowedRedirectUrls: https://admin.eshoponabp.com
  authServer:
    authority: https://auth.eshoponabp.com
    requireHttpsMetadata: "false"
  connectionStrings:
    administrationService: "Host=eshop-az-postgresdb;Port=5432;Database=EShopOnAbp_Administration;User ID=postgres;password=myPassw0rd;Pooling=false"
    identityService: "Host=eshop-az-postgresdb;Port=5432;Database=EShopOnAbp_Identity;User ID=postgres;password=myPassw0rd;Pooling=false"
  dotnetEnv: Production
  redisHost: eshop-az-redis
  rabbitmqHost: eshop-az-rabbitmq
  elasticsearchHost: eshop-az-elasticsearch
ingress:
  host: auth.eshoponabp.com
  tlsSecret: eshop-wildcard-tls
image:
  repository: "volocr.azurecr.io/eshoponabp/app-authserver"
  tag: 1.0.5