apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      containers:
        - image: consul
          name: {{ .Release.Name }}-{{ .Chart.Name }}
          ports:
            - name: consul-1
              protocol: TCP
              containerPort: 8500
            - name: consul-2
              protocol: TCP
              containerPort: 8600