config:
  selfUrl: https://www.eshoponabp.com
  gatewayUrl: "https://gateway.eshoponabp.com/"
  authServer:
    authority: https://auth.eshoponabp.com
    requireHttpsMetadata: "false"
  dotnetEnv: Staging
  redisHost: es-st-redis
  rabbitmqHost: es-st-rabbitmq
  elasticsearchHost: es-st-elasticsearch
  stringEncryptionDefaultPassPhrase: gsKnGZ041HLL4IM8

ingress:
  host: eshop-st-public-web
  tlsSecret: eshop-wildcard-tls

image:
  repository: eshoponabp/app-publicweb
  tag: latest
  pullPolicy: IfNotPresent

env: {}
