  env:
    - name: "App__SelfUrl"
      value: "https://eshop-st-identity"
    - name: "App__CorsOrigins"
      value: "https://eshop-st-gateway-web,https://eshop-st-gateway-public-web,https://eshop-st-gateway-internal"
    - name: "IdentityServerClients__Web__RootUrl"
      value: "https://eshop-st-web/"
    - name: "IdentityServerClients__PublicWeb__RootUrl"
      value: "https://eshop-st-public-web/"
    - name: "IdentityServerClients__IdentityService__RootUrl"
      value: "https://eshop-st-identity/"
    - name: "IdentityServerClients__SaasService__RootUrl"
      value: "https://eshop-st-saas/"
    - name: "IdentityServerClients__AdministrationService__RootUrl"
      value: "https://eshop-st-administration/"
    - name: "IdentityServerClients__InternalGateway__RootUrl"
      value: "https://eshop-st-gateway-internal/"
    - name: "IdentityServerClients__PublicWebGateway__RootUrl"
      value: "https://eshop-st-gateway-public-web/"
    - name: "IdentityServerClients__WebGateway__RootUrl"
      value: "https://eshop-st-gateway-web/"
    