config:
  selfUrl: # https://eshop-st-administration
  gatewayUrl: # https://eshop-st-gateway-internal/
  corsOrigins: # https://eshop-st-gateway-web,https://eshop-st-gateway-public-web,https://eshop-st-gateway-internal
  identityClientAuthority: # https://eshop-st-authserver
  connString: # 
  saasService:
    connString: # 
  dotnetEnv: # 
  redisHost: #
  rabbitmqHost: #
  elasticsearchHost: #
  authServerAuthority: #
  authServerRequireHttpsMetadata: #
  stringEncryptionDefaultPassPhrase: #

ingress:
  host: # eshop-st-administration
  tlsSecret: eshop-demo-tls

image:
  repository: eshoponabp/service-administration
  tag: latest
  pullPolicy: IfNotPresent

env: {}
